docs/AboutUs.md
Add my name and github url to AboutUs.md
=> Edit aboutus readme

docs/AboutUs.md
=> Add name in AboutUs - Vignesh

build.gradle, src/main/java/seedu/mtracker/MTracker.java, src/main/java/seedu/mtracker/commands/AddCryptoCommand.java, src/main/java/seedu/mtracker/commands/AddEtfCommand.java, src/main/java/seedu/mtracker/commands/AddForexCommand.java, src/main/java/seedu/mtracker/commands/AddInstrumentCommand.java, src/main/java/seedu/mtracker/commands/AddStockCommand.java, src/main/java/seedu/mtracker/commands/Command.java, src/main/java/seedu/mtracker/commands/ListCommand.java, src/main/java/seedu/mtracker/console/AddCryptoParser.java, src/main/java/seedu/mtracker/console/AddEtfParser.java, src/main/java/seedu/mtracker/console/AddForexParser.java, src/main/java/seedu/mtracker/console/AddInstrumentParser.java, src/main/java/seedu/mtracker/console/AddStockParser.java, src/main/java/seedu/mtracker/console/InputParser.java, src/main/java/seedu/mtracker/instrument/Instrument.java, src/main/java/seedu/mtracker/instrument/InstrumentManager.java, src/main/java/seedu/mtracker/instrument/subinstrument/Crypto.java, src/main/java/seedu/mtracker/instrument/subinstrument/Etf.java, src/main/java/seedu/mtracker/instrument/subinstrument/Forex.java, src/main/java/seedu/mtracker/instrument/subinstrument/Stock.java, src/main/java/seedu/mtracker/ui/TextUi.java, src/test/java/seedu/mtracker/MTrackerTest.java
Added the relevant classes and organised them for starting the development of MVP features. Change the name of main class and test class to use our project name
Fixes: #12
=> Create basic classes and packages

src/main/java/seedu/mtracker/MTracker.java, src/main/java/seedu/mtracker/commands/AddCryptoCommand.java, src/main/java/seedu/mtracker/commands/AddEtfCommand.java, src/main/java/seedu/mtracker/commands/AddForexCommand.java, src/main/java/seedu/mtracker/commands/AddInstrumentCommand.java, src/main/java/seedu/mtracker/commands/AddStockCommand.java, src/main/java/seedu/mtracker/commands/Command.java, src/main/java/seedu/mtracker/commands/ListCommand.java, src/main/java/seedu/mtracker/instrument/Instrument.java, src/main/java/seedu/mtracker/instrument/InstrumentManager.java, src/main/java/seedu/mtracker/instrument/subinstrument/Crypto.java, src/main/java/seedu/mtracker/instrument/subinstrument/Etf.java, src/main/java/seedu/mtracker/instrument/subinstrument/Forex.java, src/main/java/seedu/mtracker/instrument/subinstrument/Stock.java
Added instrument manager, instrument class and command baselines
Added crypto class
=> Added instrument class, instrument manager and command baselines and crypto class

src/main/java/seedu/mtracker/MTracker.java, src/main/java/seedu/mtracker/commands/AddCryptoCommand.java, src/main/java/seedu/mtracker/commands/AddEtfCommand.java, src/main/java/seedu/mtracker/commands/AddForexCommand.java, src/main/java/seedu/mtracker/commands/AddInstrumentCommand.java, src/main/java/seedu/mtracker/commands/AddStockCommand.java, src/main/java/seedu/mtracker/commands/Command.java, src/main/java/seedu/mtracker/commands/ExitCommand.java, src/main/java/seedu/mtracker/commands/ListCommand.java, src/main/java/seedu/mtracker/console/AddInstrumentParser.java, src/main/java/seedu/mtracker/console/AddStockParser.java, src/main/java/seedu/mtracker/console/InputParser.java, src/main/java/seedu/mtracker/error/ErrorMessage.java, src/main/java/seedu/mtracker/instrument/Instrument.java, src/main/java/seedu/mtracker/instrument/InstrumentManager.java, src/main/java/seedu/mtracker/instrument/subinstrument/Crypto.java, src/main/java/seedu/mtracker/ui/TextUi.java
- InputParser class is the class that handles the different types of commands like add, list, delete etc
- AddInstrumentParser class handles specific commands related to add, like add stock etc.
- The AddInstrumentParser class handles general parameters that has to be added for all instruments
- The child classes like addForexParser etc can follow addStockParser
Should be merged after https://github.com/AY2122S1-CS2113T-T12-1/tp/pull/19
fixes: #13
=> Update parser class to handle add instrument commands

src/main/java/seedu/mtracker/console/AddCryptoParser.java, src/main/java/seedu/mtracker/error/ErrorMessage.java, src/test/java/seedu/mtracker/console/AddCryptoParserTest.java, src/test/java/seedu/mtracker/console/AddStockParserTest.java
Added junit testing for crypto functionalities
=> Added AddCryptoParser Junit test

src/main/java/seedu/mtracker/console/AddInstrumentParser.java, src/main/java/seedu/mtracker/error/ErrorMessage.java, src/test/java/seedu/mtracker/console/AddForexParserTest.java
=> Added Junit tests for AddForexParser and updated error message for invalid fx name

src/main/java/seedu/mtracker/asserthelpers/AssertParserHelper.java, src/main/java/seedu/mtracker/console/AddForexParser.java
=> Assertions added for AddForexParser

src/main/java/seedu/mtracker/asserthelpers/AssertParserHelper.java, src/main/java/seedu/mtracker/console/AddEtfParser.java
=> Add Assertion for Etf Parser

docs/UserGuide.md
Here is the link to the userguide
https://github.com/theodorekwok/tp/blob/theodorekwok-userguide-first-update/docs/UserGuide.md
Things need, a content page
Please provide any feedback or things to improve on. 
links to #71
=> Update user guide with add stock instruction

build.gradle, src/main/java/seedu/mtracker/MTracker.java
=> Enable assertions in build.gradle file

docs/DeveloperGuide.md
Wrote up design section for Ui component
=> Update UI component section in DG design

src/main/java/seedu/mtracker/model/Instrument.java, src/main/java/seedu/mtracker/model/subinstrument/Crypto.java, src/main/java/seedu/mtracker/model/subinstrument/Etf.java, src/main/java/seedu/mtracker/model/subinstrument/Forex.java
Code Quality improvement: All redundant getters that are self-involked in instrument classes removed.
=> Remove unnecessary getters

src/main/java/seedu/mtracker/commands/DeleteCommand.java, src/main/java/seedu/mtracker/commands/DoneCommand.java, src/main/java/seedu/mtracker/commands/EditInstrumentCommand.java, src/main/java/seedu/mtracker/commands/IndexedCommand.java, src/main/java/seedu/mtracker/commands/ViewCommand.java, src/main/java/seedu/mtracker/commons/Validate.java, src/main/java/seedu/mtracker/console/InputParser.java, src/main/java/seedu/mtracker/error/AlreadyDoneError.java, src/main/java/seedu/mtracker/error/ErrorMessage.java, src/main/java/seedu/mtracker/filemanager/InstrumentDecoder.java, src/main/java/seedu/mtracker/model/Instrument.java, src/main/java/seedu/mtracker/model/InstrumentManager.java, src/test/java/seedu/mtracker/console/InputParserTest.java
Code Quality improvement: Created IndexedCommand abstract class for delete, done, edit, view commands.
Fix #194
=> Abstract out indexed commands

src/main/java/seedu/mtracker/MTracker.java, src/main/java/seedu/mtracker/console/AddCryptoParser.java, src/main/java/seedu/mtracker/console/AddEtfParser.java, src/main/java/seedu/mtracker/console/AddForexParser.java, src/main/java/seedu/mtracker/console/AddInstrumentParser.java, src/main/java/seedu/mtracker/console/AddStockParser.java, src/main/java/seedu/mtracker/console/EditInstrumentParser.java, src/main/java/seedu/mtracker/console/InputParser.java, src/main/java/seedu/mtracker/ui/TextUi.java, text-ui-test/EXPECTED.TXT
Included current workspace in prompters to improve user experience.
Fix #117
=> Add current workspace to prompter

src/main/java/seedu/mtracker/commons/Validate.java, src/main/java/seedu/mtracker/console/InputParser.java, src/main/java/seedu/mtracker/error/ErrorMessage.java, src/main/java/seedu/mtracker/error/InvalidNegativePriceError.java, src/main/java/seedu/mtracker/error/InvalidPriceError.java
… exception handling non-number inputs for price
added valid instrument chechks in validate
links #186
=> added exception to handle negative or 0 current price. Added ability to run multiple invalid inputs into instrument type

src/main/java/seedu/mtracker/commands/FindCommand.java, src/main/java/seedu/mtracker/console/InputParser.java, src/main/java/seedu/mtracker/error/InvalidEmptySearchStringError.java, src/main/java/seedu/mtracker/ui/TextUi.java
Find command now searches for the whole longer string user keys in rather just the first word.
Fix #184 
Fix #174
=> Enable find with more than one search word

src/main/java/seedu/mtracker/commons/Validate.java, src/main/java/seedu/mtracker/error/ErrorMessage.java, src/main/java/seedu/mtracker/ui/TextUi.java
Made error messages more specific. Removed confusing info.
Fix #157 
Fox #173
=> Specific error messages

src/main/java/seedu/mtracker/filemanager/CryptoDecoder.java, src/main/java/seedu/mtracker/filemanager/EtfDecoder.java, src/main/java/seedu/mtracker/filemanager/ForexDecoder.java, src/main/java/seedu/mtracker/filemanager/InstrumentDecoder.java, src/main/java/seedu/mtracker/filemanager/InstrumentEncoder.java, src/main/java/seedu/mtracker/filemanager/StockDecoder.java, src/main/java/seedu/mtracker/filemanager/Storage.java
=> added java docs for filemanager

src/main/java/seedu/mtracker/commands/EditInstrumentCommand.java, src/main/java/seedu/mtracker/console/EditInstrumentParser.java
=> JavaDoc for edited class

docs/AboutUs.md, docs/README.md
need to create links so that ppp can be seen in the github pages
=> Create links and update readme

src/main/java/seedu/mtracker/console/AddCryptoParser.java, src/main/java/seedu/mtracker/console/AddEtfParser.java, src/main/java/seedu/mtracker/console/AddForexParser.java, src/main/java/seedu/mtracker/console/AddInstrumentParser.java, src/main/java/seedu/mtracker/console/AddStockParser.java, src/main/java/seedu/mtracker/console/EditInstrumentParser.java, src/main/java/seedu/mtracker/console/InputParser.java
=> Add javadocs for console

docs/AboutUs.md
The current ppp link doesnt work, hopefully this fixes it
=> update link path

docs/UserGuide.md
=> final edits to ug

src/main/java/seedu/mtracker/MTracker.java
Added some javadoc comments for MTracker.java
=> Add javadoc to MTracker.java
